export const VIEW_COUNT_FETCH: string = 'VIEW_COUNT_FETCH';
export const VIEW_COUNT_UPDATE: string = 'VIEW_COUNT_UPDATE';
export const VIEW_COUNT_UPDATE_CURRENT_TIME: string = 'VIEW_COUNT_UPDATE_CURRENT_TIME';
export const VIEW_COUNT_SAVE_INTERVAL: string = 'VIEW_COUNT_SAVE_INTERVAL';
export const VIEW_COUNT_SERVICE_REGISTER: string = 'VIEW_COUNT_SERVICE_REGISTER';
export const VIEW_COUNT_SERVICE_UNREGISTER: string = 'VIEW_COUNT_SERVICE_UNREGISTER';
