export const VIDEO_PLAYER_INIT: string = 'VIDEO_PLAYER_INIT';
export const VIDEO_PLAYER_RESIZE: string = 'VIDEO_PLAYER_RESIZE';
export const VIDEO_PLAYER_CURRENT_TIME_UPDATE: string = 'VIDEO_PLAYER_CURRENT_TIME_UPDATE';
export const VIDEO_PLAYER_SEEK: string = 'VIDEO_PLAYER_SEEK';
export const VIDEO_PLAYER_DESTORY: string = 'VIDEO_PLAYER_DESTORY';

export const VIDEO_PLAYER_SELECT_HIGHLIGHT_COLOR: string = 'VIDEO_PLAYER_SELECT_HIGHLIGHT_COLOR';
export const VIDEO_PLAYER_PLAY_HIGHLIGHT_START: string = 'VIDEO_PLAYER_PLAY_HIGHLIGHT_START';
export const VIDEO_PLAYER_PLAY_NEXT_HIGHLIGHT_INTERVAL: string = 'VIDEO_PLAYER_PLAY_NEXT_HIGHLIGHT_INTERVAL';
export const VIDEO_PLAYER_COMMENT_CLICK: string = 'VIDEO_PLAYER_COMMENT_CLICK';
export const VIDEO_PLAYER_PLAY_NEXT_COMMENT_INTERVAL: string = 'VIDEO_PLAYER_PLAY_NEXT_COMMENT_INTERVAL';
