version: '2'

services:
  node:
      build:
        context: .
        dockerfile: ./Dockerfile/DockerfileDevelop
      ports:
        - "8080:8080"
      links:
        - mongodb
      volumes:
        - ./client:/app/client
        - ./server:/app/server
        - ./config:/app/config
        - ./index.html:/app/index.html
        - ./webpack.dev.config.js:/app/webpack.dev.config.js
        - ./package.json:/app/package.json
      container_name: ViDeX-Dev-App-Container
      command: yarn run test

  mongodb:
      image: mongo:latest
      container_name: ViDex-Dev-MongoDB-Container
