export const TRANSCRIPT_SEARCH_WORD: string = 'TRANSCRIPT_SEARCH_WORD';
export const TRANSCRIPT_INIT: string = 'TRANSCRIPT_INIT';

export const SHOW_COMMENT_INTERVAL_WORD: string = 'SHOW_COMMENT_INTERVAL_WORD';

export const HIDE_COMMENT_INTERVAL_WORD: string = 'HIDE_COMMENT_INTERVAL_WORD';

export const TRANSCRIPT_UPDATE: string = 'TRANSCRIPT_UPDATE';
